Updated pixi-version
Fixes following error on pipeline:
```
  Error:   × Lock-file version 7 is newer than supported
    help: Maximum supported version: 6 (pixi v0.63.2)
          Cannot continue with --locked or --frozen mode as the lock-file cannot be read.
          Try running `pixi self-update` to update to the latest version.
```